export default {
    id: "id",
    code: "code",
    _order: "order",
    startDate: "startDate",
    endDate: "endDate",
    vehicle: "vehicle",
    driver: "driver",
    trailer: "trailer",
    sysrefTransportationType: "sysrefTransportationType",
    sysrefVoyageDirection: "sysrefVoyageDirection",
    loadingLocation: "loadingLocation",
    dumpingLocation: "dumpingLocation",
    substitudeDriver: "substitudeDriver",
    transportWaybillNo: "transportWaybillNo",
    deliveryNoteNo: "deliveryNoteNo",
    sasNumber: "sasNumber",
    sysrefDeliveryStatus: "sysrefDeliveryStatus",
    active: "active",
    calculatedRoute: "calculatedRoute",
    optimizationParameters: 'optimizationParameters',
    sortedVendors: 'sortedVendors'
}
