export default {
    id: 'code',
    name: 'name',
    title: 'title',
    sysrefCountry: 'sysrefCountry',
    sysrefCity: 'sysrefCity',
    sysrefDistrict: 'sysrefDistrict',
    address: 'address',
    phone: 'phone',
    phone2: 'phone2',
    fax: 'fax',
    gsm: 'gsm',
    webAddress: 'webAddress',
    email: 'email',
    refCompanySector: 'refCompanySector',
    customerRepresentative: 'customerRepresentative',
    numberOfStaff: 'numberOfStaff',
    employerRegistrationNo: 'employerRegistrationNo',
    tradeRegistrationNo: 'tradeRegistrationNo',
    taxOffice: 'taxOffice',
    taxNumber: 'taxNumber',
    active: 'active'
}
