export default {
    id: 'code',
    firstName: 'firstName',
    middleName: 'middleName',
    lastName: 'lastName',
    refStaffTitle: 'refStaffTitle',
    tcIdNumber: 'tcIdNumber',
    // birthDate: 'birthDate',
    gsmNo: 'gsmNo',
    homePhone: 'homePhone',
    email: 'email',
    sysrefCountry: 'sysrefCountry',
    sysrefCity: 'sysrefCity',
    sysrefDistrict: 'sysrefDistrict',
    address: 'address',
    sysrefStaffContractType: 'sysrefStaffContractType',
    drivingLicenseNumber: 'drivingLicenseNumber',
    sysrefDrivingType: 'sysrefDrivingType',
    active: 'active'
}
